### ISSUE TITLE
UnitType toString fails?

### ISSUE THREAD

**Issue by IannothSlurgh** [vjurenka/BWMirror#27]
In Eclipse 4.4.2 running Java SE 1.8 with Mirror version 2.5 and BWAPI version 4.1.2 on Windows 7 x64.

Exception in thread "main" java.lang.UnsatisfiedLinkError: bwapi.UnitType.toString_native(J)Ljava/lang/String;
    at bwapi.UnitType.toString_native(Native Method)
    at bwapi.UnitType.toString(UnitType.java:19)
    at TestBot1.main(TestBot1.java:973)

Line 973 of TestBot1.java is:
System.out.println(UnitType.Zerg_Zergling.toString());

Being able to print UnitType without running it through a self-made switch case would be useful for debugging purposes.

Strangely enough, when I take an actual unit in game and attempt to print its unit type, things are OK. For instance, the line below works.

System.out.println("New unit " + unit.getType());

**Comment by RobinsonMann** [comment]
Hey I just ran into the same issue and I was wondering if you made any progress on it. Thanks.

**Comment by Ravaelles** [comment]
In cases like this I choose not to lose my precious time and implement my own "toString" solution using a function like "getName".

`Strangely enough, when I take an actual unit in game and attempt to print its unit type, things are OK`
To me it clearly indicates that probably it's being populated in the moment the game is started. Anyway, you're unlikely to solve it without some extra effort.

**Comment by IannothSlurgh** [comment]
While this problem with bwmirror is not currently fixed, I programmed a work around like Mr. Ravaelles suggested after I had first discovered the issue.

If you use map data structures, you can use them to convert between UnitType.Zerg_Zergling and "Zerg_Zergling" For example:

```
HashMap<UnitType, String> converter = new HashMap<UnitType, String>();
converter.put(UnitType.Zerg_Zergling,"Zerg_Zergling");

UnitType unitTypeToConvert = UnitType.Zerg_Zergling;
String answer = null;

if(converter.containsKey(unitTypeToConvert))
{
    answer = converter.get(unitTypeToConvert);
}

System.out.println(answer);
```

The ugliest feature of this solution is that you have to call the put function roughly 90 times in order to cover all melee units and buildings.

**Comment by RobinsonMann** [comment]
I spent a little bit of time working on this problem and I think I found the cause. 

The methods that we are looking for are in "bwapi_bridge2_5.dll". Since we aren't loading this library, we are getting the linking errors. In one line, the solution to this is to call "System.loadLibrary("bwapi_bridge2_5.dll")";

Now, if everything loads correctly, when you call toString you will now get a "EXCEPTION_ACCESS_VIOLATION" JVM error. 

My understanding is that this is called by bad pointers. 

I spent a little bit of time researching the code and from what I understand, when you call Mirror.run() the internal C++ UnitType objects have their addresses passed to the corresponding Java objects (The pointer to the C++ UnitType is saved in the "pointer" field in the Java object). When you call toString on the java Object, what it does is calls a C++ method that takes in the CppUnitTypePointer and then calls "toString" on that. 

Since we never ran the code to link the objects, the CppUnitTypePointer inside the Java UnitTypes will be incorrect, so when call the C++ toString method with that pointer we get an EXCEPTION_ACCESS_VIOLATION error. 

Unfortunately, the code that sets the C++ UnitType pointers inside the Java objects is inside Mirror.run(), as far as I can tell, it doesn't seem possible to just call it for setting the objects and not starting the game.

A possible solution to the problem is to move all of the setup code to a new method, and when a unit test requires that the Java objects work, it can call the setup method. 

A more 'far out' solution would be to somehow get Java to find the addresses of the C++ objects in memory, and manually set the pointer field to the address.

**Comment by adakitesystems** [comment]
The following command works for me and executes as expected without errors: `System.out.println(UnitType.Zerg_Zergling.toString());`. 

I'm using Win 7 32-bit, BWAPI 4.1.2, BWMirror 2.5, Oracle JDK 1.8u111, NetBeans 8.2

**Comment by IannothSlurgh** [comment]
@adakitesystems Could you tell us when it works? What I mean is, are you running the command after the game has started or before?

While my memory is a little faded on the issue, I think we figured out that the problem was at least partially caused by running the command before the game starts.

**Comment by adakitesystems** [comment]
Right, I think it may only work when called from the "onStart" or "onFrame" callback functions as demonstrated in this modified [example bot](https://gist.github.com/adakitesystems/fe9c684fb65290040614ac96e788d3a8).
